ARG OPENSEARCH_VERSION
FROM opensearchproject/opensearch:$OPENSEARCH_VERSION

ARG plugin_path=/usr/share/plugins/plugin
ARG opensearch_path=/usr/share/opensearch
ARG opensearch_yml=$opensearch_path/config/opensearch.yml

RUN rm -f $opensearch_path/config/scripts

COPY --chown=opensearch:opensearch .ci/opensearch-run.sh $opensearch_path/
